[options]
graphical           = false
submission_files    = ["example-no-errors.py", "example-with-errors.py", "example-not-in-submission.py"]
root_directory      = "/autograder"

[deadlines]
release_date    = 2026-01-01 23:59:59
due_date        = 2111-01-01 23:59:59
final_due_date  = 2222-01-01 23:59:59
