#!/usr/bin/env bash
set -oue pipefail
shopt -s nullglob

###################################
### Script Usage and Parameters ###
###################################

help_message() {
    echo "Usage: $0 [-h] [GRADING_DIRECTORY]"
    echo "Runner for local gradescope emulation. Runs autograding tests by default."
    echo ""
    echo "params:"
    echo "GRADING_DIRECTORY     Use instead of default (./submissions)"
    echo ""
    echo "options:"
    echo "-h                    Print this help message."
    echo "-r                    Generate rubric (before running all tests)."
    echo "-a                    Autograding tests."
    echo "-i                    Interactive (manual and autotests)."
    echo "-s                    Skip submissions that have already been graded."
    echo "-f                    Generate feedback markdown/csv (after running all tests)."
    echo "-p                    Generate pdf during feedback generation."
    echo
}

interactive=false
feedback=false
rubric=false
auto=false
skip=false
pdf=false

while getopts ":hifrsp" o; do case "${o}" in
    h) help_message && exit 0 ;;
    i) interactive=true ;;
    f) feedback=true ;;
    r) rubric=true ;;
    s) skip=true ;;
    p) pdf=true ;;
    a) auto=true ;;
    \?) printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
esac done

shift $((OPTIND - 1));

###################################
### Script ###
###################################

AUTOGRADE_SCRIPT="run_tests.py"
MANUALGRADE_SCRIPT="run_manualgrader.py"
FEEDBACK_SCRIPT="run_feedback_generator.py"
GRADING_DIR="${1:-submissions}"

PDF_CSS="../../utils/pdf.css"
SOLUTION_FOLDER="AAASOLUTIONZZZ"
TEST_ANSWER_FILE="test_answers.txt"

cur=$PWD
args=("$@")
declare -a student_files

function get_student_files {
  local student_dir="${1}"
  mapfile -t -d '' student_files < <(find ${student_dir} -type f -print0)
  for file in "${student_files[@]}"; do cp "${file}" .; done
}

function clean_student_files {
  for file in "${student_files[@]}"; do rm "$(basename ${file})"; done
}

function autograde {
  local student_dir="${1}"
  echo -n "autograding ${student_dir}..."
  python ${AUTOGRADE_SCRIPT} ${student_dir} || error "Error caught: cleaning student files and exiting."
  grep score "${student_dir}/results.json" | tail -n 1 || echo "No score in results.json. Whatever."
}

function manualgrade {
  local student_dir="${1}"
  python ${MANUALGRADE_SCRIPT} ${student_dir} || error "Error caught: cleaning student files and exiting."
}

function interactivegrade {
  local student_dir="${1}"
  autograde $student_dir
  manualgrade $student_dir
  read -p "Rerun and reapply autogrades? y/n: " grade_this_dir
  while [[ ${grade_this_dir} == "y" ]]; do
    clean_student_files
    get_student_files $student_dir
    autograde $student_dir
    manualgrade $student_dir
    read -p "Rerun and reapply autogrades? y/n: " grade_this_dir
  done
  echo "On to the next student."
}

function generate_pdf {
  local feedback_file="${1}"
  PANDOC_OPTS=( --standalone --highlight-style=kate --from=commonmark_x --to=html5 )
  WEASYPRINT_OPTS=( --stylesheet "${PDF_CSS}" --quiet )
  echo "Generating pdf ${feedback_file%.*}.pdf"
  pandoc "${PANDOC_OPTS[@]}" "${feedback_file}" | weasyprint "${WEASYPRINT_OPTS[@]}" - - > "${feedback_file%.*}.pdf"
}

function generate_feedback {
  local student_dir="${1}"
  echo "generating feedback for ${student_dir}..."
  python ${FEEDBACK_SCRIPT} ${student_dir} 0 || error "Error caught: cleaning student files and exiting."
  local feedback_file=$(find ${student_dir} -type f -name "*.md")
  mdformat ${feedback_file}
  if ${pdf}; then
    generate_pdf ${feedback_file}
  fi
}

function generate_rubric {
  local student_dir="${1}"
  autograde $student_dir
  manualgrade $student_dir
  python ${FEEDBACK_SCRIPT} ${student_dir} 1 || error "Error caught: cleaning student files and exiting."
}

function grade_student_dir {
  local student_dir="${1}"
  if ${interactive}; then
    get_student_files $student_dir
    interactivegrade $student_dir
    clean_student_files
  elif ${auto}; then
    get_student_files $student_dir
    autograde $student_dir
    clean_student_files
  elif ${rubric}; then
    get_student_files $student_dir
    generate_rubric $student_dir
    clean_student_files
  elif ${feedback}; then
    get_student_files $student_dir
    generate_feedback $student_dir
    clean_student_files
  fi
}

function error() {
  printf "%s\n" "$1" >&2
  clean_student_files
  exit 1
}

trap ctrl_c INT
function ctrl_c() {
  echo ""
  echo "SIGINT caught: cleaning student files before exiting."
  clean_student_files
  exit 0
}

if ${rubric}; then
  student_dir=$(find ${GRADING_DIR} -mindepth 1 -maxdepth 1 -type d -name "*${SOLUTION_FOLDER}*")
  grade_student_dir "${student_dir}/"
else
  mapfile -t -d '' dirs < <(find ${GRADING_DIR} -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)
  mapfile -t -d '' already_graded < <(find ${GRADING_DIR} -type f -name "${TEST_ANSWER_FILE}" -exec dirname {} \; | sort)
  if ${skip}; then
    dirs=($(comm --nocheck-order -3 <(printf "%s\n" "${dirs[@]}") <(printf "%s\n" "${already_graded[@]}")))
    echo "Skipping the following directories (already graded):"
    printf '%s\n' "${already_graded[@]}"
  elif ${feedback}; then
    dirs=(${already_graded[@]})
    echo "Only considering the following directories (already graded):"
    printf '%s\n' "${dirs[@]}"
  fi
  for D in "${dirs[@]}"; do grade_student_dir "${D}/"; done
fi

