#!/usr/bin/env bash
set -oue pipefail
shopt -s nullglob

interactive=false
feedback=false
rubric=false

###################################
### Script Usage and Parameters ###
###################################

help_message() {
    echo "Usage: $0 [-h] [GRADING_DIRECTORY]"
    echo "Runner for local gradescope emulation. Runs autograding tests by default."
    echo ""
    echo "options:"
    echo "-h                    Print this help message."
    echo "-r                    Generate rubric (before running all tests)."
    echo "-i                    Interactive (manual and autotests)."
    echo "-f                    Generate feedback (after running all tests)."
    echo "GRADING_DIRECTORY     Use instead of default."
    echo
}

while getopts ":hifr" o; do case "${o}" in
    h) help_message && exit 0 ;;
    i) interactive=true ;;
    f) feedback=true ;;
    r) rubric=true ;;
    \?) printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
esac done

shift $((OPTIND - 1));

AUTOGRADE_SCRIPT="run_tests.py"
MANUALGRADE_SCRIPT="run_manualgrader.py"
FEEDBACK_SCRIPT="run_feedback_generator.py"
GRADING_DIR="${1:-submissions}"
PDF_CSS="pdf.css"

###################################
### Script ###
###################################

cur=$PWD
args=("$@")
declare -a student_files

function get_student_files {
  local student_dir="${1}"
  mapfile -t -d '' student_files < <(find ${student_dir} -name '*.py' -print0)
  for file in "${student_files[@]}"; do cp "${file}" .; done
}

function clean_student_files {
  for file in "${student_files[@]}"; do rm "$(basename ${file})"; done
}

function autograde {
  local student_dir="${1}"
  echo -n "autograding ${student_dir}..."
  python ${AUTOGRADE_SCRIPT} ${student_dir} || error "Error caught: cleaning student files and exiting."
  grep score "${student_dir}/results.json" | tail -n 1 | column -t
}

function manualgrade {
  local student_dir="${1}"
  python ${MANUALGRADE_SCRIPT} ${student_dir} || error "Error caught: cleaning student files and exiting."
}

function interactivegrade {
  local student_dir="${1}"
  autograde $student_dir
  manualgrade $student_dir
  read -p "Rerun and reapply autogrades? y/n" grade_this_dir
  if [[ ${grade_this_dir} == "y" ]]; then
    clean_student_files
    get_student_files $student_dir
    autograde $student_dir
    manualgrade $student_dir
  fi
  echo "On to the next student."
}

function generate_feedback {
  local student_dir="${1}"
  echo "generating feedback for ${student_dir}..."
  python ${FEEDBACK_SCRIPT} ${student_dir} 0 || error "Error caught: cleaning student files and exiting."
  local feedback_file=$(find ${student_dir} -type f -name "*.md")
  # mdformat ${feedback_file}
  PANDOC_OPTS=( --standalone --highlight-style=kate --from=commonmark_x --to=html5 )
  WEASYPRINT_OPTS=( --stylesheet "${PDF_CSS}" )
  pandoc "${PANDOC_OPTS[@]}" "${feedback_file}" | weasyprint "${WEASYPRINT_OPTS[@]}" - - > "${feedback_file%.*}.pdf"
}

function generate_rubric {
  local student_dir="${1}"
  autograde $student_dir
  manualgrade $student_dir
  python ${FEEDBACK_SCRIPT} ${student_dir} 1 || error "Error caught: cleaning student files and exiting."
}

function grade_student_dir {
  local student_dir="${1}"
  get_student_files $student_dir
  if ${interactive}; then
    interactivegrade $student_dir
  elif ${rubric}; then
    generate_rubric $student_dir
  elif ${feedback}; then
    generate_feedback $student_dir
  else
    autograde $student_dir
  fi
  clean_student_files
}


function error() {
  printf "%s\n" "$1" >&2
  clean_student_files
  exit 1
}

trap ctrl_c INT
function ctrl_c() {
  echo ""
  echo "SIGINT caught: cleaning student files before exiting."
  clean_student_files
  exit 0
}

if ${rubric}; then
  student_dir=$(find ${GRADING_DIR} -mindepth 1 -maxdepth 1 -type d -name "*AAASOLUTIONZZZ*")
  grade_student_dir "${student_dir}/"
else
  mapfile -t -d '' dirs < <(find ${GRADING_DIR} -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)
  for D in "${dirs[@]}"; do grade_student_dir "${D}/"; done
fi

