#!/usr/bin/env bash

# Remove unecessary folders and temporary folders
echo "finding and removing .idea"
find . -type d -name '.idea' -exec rm -r {} \;

echo "finding and removing venv"
find . -type d -name 'venv' -exec rm -rf {} \;

echo "finding and removing .venv"
find . -type d -name '.venv' -exec rm -rf {} \;

echo "finding and removing __MACOSX"
find . -type d -name '__MACOSX' -exec rm -rf {} \;

echo "finding and removing __pycache__"
find . -type d -name '__pycache__' -exec rm -rf {} \;


# Copies recursively the student files into the autograder folder 
echo "Moving the student files into the source folder"
find . -name '*.py' -exec cp {} /autograder/source/ \; 
find . -name '*.pdf' -exec cp {} /autograder/source/ \;
find . -name '*.docx' -exec cp {} / autograder/source/ \;
find . -name '*.doc' -exec cp {} / autograder/source/ \;
find . -name '*.jpeg' -exec cp {} / autograder/source/ \;
find . -name '*.png' -exec cp {} /autograder/source/ \;

cd /autograder/source
xvfb-run -a python3 run_tests.py
