from datetime import datetime

from grading import Grading
from feedback_utils import get_student_info_from_lea, give_feedback, Student
import os
import sys
import json

files = ["my_functions.py", "assignment3.py"]
due_date = datetime(2025, 11, 12, 1)

# ===============================================================================
# ENTRY POINT
# ===============================================================================

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("student submission directory AND rubric flag needed. Exiting.")
        sys.exit(1)
    path = sys.argv[1]
    rubric_generator = bool(int(sys.argv[2]))

    pathname = os.path.abspath(path)
    dirs = pathname.split(os.sep)

    manual_grading_answers = f"{path}test_answers.txt"
    generated_rubric_file = "autogenerated_rubric.json"
    true_rubric_file = "rubric.json"

    grading = Grading.de_serialize(manual_grading_answers)

    student: Student = get_student_info_from_lea(dirs[-1], due_date)
    grading.days_late = student.days_late

    if rubric_generator:
        print("Updating rubric file...")
        with open(generated_rubric_file, mode="w") as f:
            rubric = {section.name: section.weight for section in grading.sections}
            json.dump(rubric, f, indent=2)
    else:
        print("Using existing rubric file...")
        with open(true_rubric_file, mode="r") as f:
            weights = json.load(f)
        for section in grading.sections:
            section.weight = weights.get(section.name, 1)
        give_feedback(student, grading, files, path)


