#!/usr/bin/env bash

# Copies recursively the student files into the autograder folder 
echo "Moving the student files into the source folder"
find . -name '*.py' -exec cp {} /autograder/source/ \; 
find . -name '*.pdf' -exec cp {} /autograder/source/ \;
find . -name '*.docx' -exec cp {} / autograder/source/ \;
find . -name '*.doc' -exec cp {} / autograder/source/ \;
find . -name '*.jpeg' -exec cp {} / autograder/source/ \;
find . -name '*.png' -exec cp {} /autograder/source/ \;

cd /autograder/source
xvfb-run -a python3 run_tests.py
