#!/usr/bin/env bash
set -oue pipefail
shopt -s nullglob

verbose=false
interactive=false

###################################
### Script Usage and Parameters ###
###################################

help_message() {
    echo "Usage: $0 [-h] [GRADING_DIRECTORY]"
    echo "Runner for local gradescope emulation."
    echo ""
    echo "options:"
    echo "-h                    Print this help message."
    echo "-v                    Verbose."
    echo "-i                    Interactive."
    echo "GRADING_DIRECTORY     Use instead of default."
    echo
}

while getopts ":h:v:i" o; do case "${o}" in
    h) help_message && exit ;;
    v) verbose=true ;;
    i) interactive=true ;;
    \?) printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
esac done

shift $((OPTIND - 1));

AUTOGRADE_SCRIPT="run_tests.py"
MANUALGRADE_SCRIPT="generate_feedback.py"
GRADING_DIR="${1:-submissions}"

###################################
### Functions ###
###################################

error() { printf "%s\n" "$1" >&2; exit 1; }

###################################
### Script ###
###################################

cur=$PWD
args=("$@")
declare -a student_files

function get_student_files {
  local student_dir="${1}"
  mapfile -t -d '' student_files < <(find ${student_dir} -name '*.py' -print0)
  for file in "${student_files[@]}"; do cp "${file}" .; done
}

function clean_student_files {
  for file in "${student_files[@]}"; do rm "$(basename ${file})"; done
}

function autograde {
  local student_dir="${1}"
  python ${AUTOGRADE_SCRIPT} ${student_dir}
  echo -n "autograding ${student_dir}..."
  grep score "${student_dir}/results.json" | tail -n 1 | column -t
}

function manualgrade {
  local student_dir="${1}"
  python ${MANUALGRADE_SCRIPT} ${student_dir}
}

function interactivegrade {
  local student_dir="${1}"
  autograde $student_dir
  read -p "Manual grade ${student_dir}? y/n: " grade_this_dir
  while [[ ${grade_this_dir} == "y" ]]; do
    manualgrade $student_dir
    echo "NOTE: you can alter the student submission at this point, it will be re-copied."
    clean_student_files
    get_student_files $student_dir
    autograde $student_dir
    read -p "regrade ${student_dir}? y/n: " grade_this_dir
  done
  echo "On to the next student."
}

function grade_student_dir {
  local student_dir="${1}"
  get_student_files $student_dir
  if ${interactive}; then
    interactivegrade $student_dir
  else
    autograde $student_dir
  fi
  clean_student_files
}

trap ctrl_c INT
function ctrl_c() {
  echo ""
  echo "SIGINT caught: cleaning student files before exiting."
  clean_student_files
  exit 0
}

mapfile -t -d '' dirs < <(find ${GRADING_DIR} -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)
for D in "${dirs[@]}"; do grade_student_dir "${D}/"; done
